### ISSUE TITLE
Policy documents for Dev & Prod environment

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#12]

**Comment by LyndonP** [comment]
Estimated Time: 3 hour
Actual Time: 1 hour

Made a sample policy for the API team as well as one for the Lambda function itself:
https://github.com/ActoKids/devops/tree/dev/scripts/iam/API

These policies will be applied to both Prod and Dev environments after approval or any needed changes.

**Comment by LyndonP** [comment]
![policiesjpg](https://user-images.githubusercontent.com/34604046/53133467-2196b680-3528-11e9-9d41-b22f4b3e32fe.jpg)

**Comment by LyndonP** [comment]
Cannot create one large policy. Will need to break it down by sub-teams. 

Using a combination of policies is the next route I'm exploring.

**Comment by LyndonP** [comment]
pr: [https://github.com/ActoKids/devops/pull/27](url)
Actual Time: 4 Hours
policies: [https://github.com/ActoKids/devops/blob/LyndonP-prod-dev-policies/scripts/iam/prod-dev-policies/ad440-w19-prod-lyndon-policy.json](url)

**Comment by LyndonP** [comment]
![policies](https://user-images.githubusercontent.com/34604046/53302130-e0e0bb00-380f-11e9-85b7-998c0a334fa7.png)

**Comment by LyndonP** [comment]
![policies_prod](https://user-images.githubusercontent.com/34604046/53311114-6ee69100-3864-11e9-9aeb-7bcd80f4eef3.png)

**Comment by LyndonP** [comment]
I ended up creating 4 policies per environment which encompasses the sub-teams policies,
   - https://github.com/ActoKids/devops/tree/LyndonP-prod-dev-policies/scripts/iam/prod-dev-policies

**Comment by LyndonP** [comment]
pr: [https://github.com/ActoKids/devops/pull/27/commits](https://github.com/ActoKids/devops/pull/27/commits)
Actual Time: 4 Hours
Testing: Waiting for confirmation that pr was successful for testing results. 
policies: [https://github.com/ActoKids/devops/tree/LyndonP-prod-dev-policies/scripts/iam/prod-dev-policies](https://github.com/ActoKids/devops/tree/LyndonP-prod-dev-policies/scripts/iam/prod-dev-policies)
wiki: (How to create an AWS policy by Amy F.) [https://github.com/ActoKids/devops/wiki/Creating-Team-Group-Policies](https://github.com/ActoKids/devops/wiki/Creating-Team-Group-Policies)

**Comment by LyndonP** [comment]
[https://github.com/ActoKids/devops/tree/LyndonP-prod-dev-policies/scripts/iam/prod-dev-policies](url)
