### ISSUE TITLE
Policy documents for API resources

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#13]

**Comment by amy61789** [comment]
Estimated Time: 1 hour
Actual Time: 25 minutes

Using the AWS policy generator made this task much easier than I expected. Policies just need to be reviewed and resources can then be deployed.

**Comment by amy61789** [comment]
Policy changes were discussed in class and just adding a Deny policy will not fix the permissions to Resource groups correctly. 
Re-wrote policies to include allow statements and also made it region specific to us-east-2.
A Test IAM Group was made called: NSC-Test-Team
All policies made for the API team were then added to this group and a test user "test-user" was added as a member of the group to do initial testing for access/permissions.

**Comment by amy61789** [comment]
**DynamoDB**
<img width="1232" alt="screen shot 2019-02-18 at 8 35 54 pm" src="https://user-images.githubusercontent.com/20174873/52990438-0d827600-33bd-11e9-8829-e2cd5cb49146.png">
<img width="1328" alt="screen shot 2019-02-18 at 8 36 35 pm" src="https://user-images.githubusercontent.com/20174873/52990439-0eb3a300-33bd-11e9-9490-6173fdd3af7a.png">

**Cognito - User Pools**
<img width="1351" alt="screen shot 2019-02-18 at 8 39 00 pm" src="https://user-images.githubusercontent.com/20174873/52990494-4884a980-33bd-11e9-92d0-4851f2a49078.png">

**Lambda**
<img width="1470" alt="screen shot 2019-02-18 at 8 40 17 pm" src="https://user-images.githubusercontent.com/20174873/52990531-710ca380-33bd-11e9-988f-38e56e1f2327.png">

**Cloudwatch**
<img width="1361" alt="screen shot 2019-02-18 at 8 42 28 pm" src="https://user-images.githubusercontent.com/20174873/52990580-c052d400-33bd-11e9-9a22-f02ffc817c62.png">

**API Gateway**
<img width="1376" alt="screen shot 2019-02-18 at 9 00 33 pm" src="https://user-images.githubusercontent.com/20174873/52991145-47a14700-33c0-11e9-8e9c-10bf6b378f03.png">

**Comment by amy61789** [comment]
[Pull Request](https://github.com/ActoKids/devops/pull/19)
[Wiki](https://github.com/ActoKids/devops/wiki/Creating-AWS-Policies)

Actual Time: 5 hours 
Deciding on how we wanted to grant access and provide resources meant a lot of other attempts until we decided on doing IAM groups. 

[Pull Request that I tested.](https://github.com/ActoKids/devops/pull/20)
Anar's Crawler Policy - made comments after testing and re-tested after he made changes.

**Comment by amy61789** [comment]
Created an additional [pull request](https://github.com/ActoKids/devops/pull/25) to specify ARN and restrict resources.
