### ISSUE TITLE
Policy documents for UI resources

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#14]
Task is to create a group policy for the UI team.

Estimated Time: 3 hours
Actual Time: 5 hours

**Comment by bmenaz** [comment]
Using the IAM Manager's Visual Policy Editor had created policy consisting of several permissions. 
Needs a review and approval followed by the attachment of policy to the UI team group.

https://github.com/ActoKids/devops/blob/dev/scripts/iam/UI/ui_team_resources_policy.json

**Comment by bmenaz** [comment]
Revisited the task instructions and made changes.
For the policy documents for UI team group - here is what I did:
- Several policies has been created in AWS for resources UI team needs. Policies hasn't been attached to UI team group for it needs an approval.

![uipolicies](https://user-images.githubusercontent.com/38149440/53120142-03b85a00-3506-11e9-814f-0ac6e36e059d.png)

- I have used the following naming convention for all the policies: ad440-w19-[aws_service]-[team]-[your_name]-policy, for example ad440-w19-s3-ui-betelhem-policy
- The policies are restricting the creation and deletion of resources and specifically the region to us-east-2. There is no restriction of region for s3 and route53.
- The policy has been checked into GitHub in the feature branch and PR has been reviewed and approved by Yahya and Anar.  They both agreed it looks good.
PR: https://github.com/ActoKids/devops/pull/18
- For the testing purposes of restrictions that apply to resources has been created a test group and test user that has those policies attached.
- I have reviewed Anar's policies for crawler team. He had two policies for two resources (Lambda and DynamoDB). I tested both of them using IAM Policy Simulator: Lambda policy had provided necessary action and passed the test, while DynamoDB had an issue with putting and deleting an item which should be allowed. Other than that everything looked good. PR: https://github.com/ActoKids/devops/pull/20
- WIKI: https://github.com/ActoKids/devops/wiki/Creating-Team-Group-Policies

![uipolicycreatetest](https://user-images.githubusercontent.com/38149440/53122095-965af800-350a-11e9-8852-7ffcdca194dc.png)

![uipolicytestdeletion](https://user-images.githubusercontent.com/38149440/53121862-0a48d080-350a-11e9-8c67-f922afe4cc64.png)

![uipolicycognitotest](https://user-images.githubusercontent.com/38149440/53122935-c1dee200-350c-11e9-8b12-9f8589e81451.png)

![uipolicycmtest](https://user-images.githubusercontent.com/38149440/53130403-ff4c6b00-351e-11e9-88b8-eae7d2e7d369.png)
