### ISSUE TITLE
Update Terraform scripts with Tags (parameters)

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#15]
Dynamo DB tf tags :
https://github.com/ActoKids/devops/blob/LyndonP-Add-terraform-tags-to-include-Environment-and-subteam/scripts/dynamodbterraform/dynamodb.tf
Lambda tf tags : 
https://github.com/ActoKids/devops/blob/LyndonP-Add-terraform-tags-to-include-Environment-and-subteam/scripts/lambdaterraform/lambdacrawler.tf
S3 tf tags : 
https://github.com/ActoKids/devops/blob/LyndonP-Add-terraform-tags-to-include-Environment-and-subteam/scripts/s3terraform/infra.tf

**Comment by LyndonP** [comment]
Added the Environment tags to closer this task out.
