### ISSUE TITLE
CI to deploy Dev and Prod environment

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#16]
Task: To finalize the CI pipelines for the Dev environment in all team branches.

Actual Time: 8 hr
Estimated Time: 8 hr

**Comment by dashinay** [comment]
Updated the Travis script for UI CI pipeline to set up a deployment for S3.
There is an issue with config.json configuration file for npm - dev branch already have one config file. To solve it I prevented initialization of npm and skipped the script run. Added a region into the travis deployment and changed the bucket name.

I will continue to work on setting up full deployment of each team scripts into the dev environment. Currently Api team Travis script is configured to work with several lambdas using the stages but deployment process is having issues. I will focus on resolving the matter.

PR: https://github.com/ActoKids/web-ui/tree/travis_s3_deploy

**Comment by dashinay** [comment]
Finished the setup of CI development pipelines for the teams:

1. Fixed up the Travis Ci pipeline for Web-UI team and made sure it is deploying into the dev s3 bucket.
PR: https://github.com/ActoKids/web-ui/pull/10
Deploy: https://travis-ci.org/ActoKids/web-ui/builds/495182458
Added an [Wiki](https://github.com/ActoKids/web-ui/wiki/Travis-CI) page for Travis pipeline.

2. Finished up a deployment into the development environment for the Crawler team.
PR: https://github.com/ActoKids/web-crawler/pull/12
Deploy: https://travis-ci.org/ActoKids/web-crawler/builds/496156692
An existing [Wiki](https://github.com/ActoKids/web-crawler/wiki/Travis-CI) page Travis pipeline.

3. Deployment into the development environment for the API team has also been completed by Bethlehem on Sprint 2.  API team Travis CI pipeline was deploying different scripts to multiple lambdas. I have double checked and it has been fixed to deploy from many on to one lambda. 
PR: https://github.com/ActoKids/api/pull/29#pullrequestreview-205921987
Deploy: https://travis-ci.org/ActoKids/api
An existing [Wiki]( https://github.com/ActoKids/api/wiki/Travis-CI) page Travis pipeline.

4. Review done by team members: 
Yahya and Betelhem has given a review to the code and had approved it. Yahya gave no feedback and Betelhem confirmed changes and suggested a change of the bucket name as I was mistaken. Yaml file was deploying the whole dev branch in WebUi repository. [PR](https://github.com/ActoKids/web-ui/pull/10)

5. Created separate ARN roles for dev and prod environments for Lambda to access specific dev s3 bucket and to specific prod s3 bucket. 

6. Updated travis ci on all team repositories and set them up to deploy to multiple environment (dev and prod). Have also updated the environmental variables to include those newly created separate ARN roles. 
UX PR: https://github.com/ActoKids/web-ui/pull/16
Crawler PR: https://github.com/ActoKids/web-crawler/pull/12
API PR: https://github.com/ActoKids/api/pull/42

**Comment by dashinay** [comment]
Web UI team Travis-CI deployment to dev environment 
![web-ui-travisci-dev](https://user-images.githubusercontent.com/34629972/53132778-9ddbca80-3525-11e9-861d-fc2c15d59fad.png)

API team Travis-CI deployment to dev environment
![api-travisci-dev](https://user-images.githubusercontent.com/34629972/53132835-ec896480-3525-11e9-805a-9a045ff46e91.png)

Crawler team Travis-CI deployment to dev environment. I have removed the dependency installation but the changes are currently in pull request.
![crawler-travisci-dev](https://user-images.githubusercontent.com/34629972/53132889-1c386c80-3526-11e9-9e8e-5b34866c19cf.png)
