### ISSUE TITLE
CloudWatch Access - API Team Request

### ISSUE THREAD

**Issue by Enshaedn** [ActoKids/devops#23]
We do not currently have access to see/create CloudWatch logs from Lambda. Please provide access to CloudWatch to our team. Note the monitoring box messages.

![image](https://user-images.githubusercontent.com/23545971/53142632-7b5ba880-3549-11e9-8285-baad050bf0f2.png)

**Comment by Enshaedn** [comment]
Follow-up request for access to CloudWatch - @LyndonP @Stakada @amy61789 @dashinay @bmenaz 

Also, we don't have access to assign labels to your repo here in GitHub.

Screen shot showing we are missing access.
![image](https://user-images.githubusercontent.com/23545971/53536620-e06c4c80-3abb-11e9-8ee2-54cee2c78f0e.png)

**Comment by amy61789** [comment]
Created fix for bug
-Cloud Formation Policy needed to be added to API Group Policy
-Lambda Role was updated to correct role: NSC-AD440-W19-LAMBDA-DEV-ENV-ROLE

Waiting on confirmation from API Team member that it is functioning as expected.

**Comment by Enshaedn** [comment]
I can see the metric charts in Lambda now, but the end goal is seeing the logs in CloudWatch and that is still not working.
![image](https://user-images.githubusercontent.com/23545971/53545315-e7a45200-3add-11e9-97d3-1ade9414ae57.png)

![image](https://user-images.githubusercontent.com/23545971/53545330-f4c14100-3add-11e9-8277-5798cd87560d.png)

**Comment by Enshaedn** [comment]
Previous errors seem to be fixed, but the logs still don't seem to be showing. 

![image](https://user-images.githubusercontent.com/23545971/53546337-e6c0ef80-3ae0-11e9-8ac1-37ec18dd610e.png)

**Comment by Enshaedn** [comment]
Amy was able to fix the issue for me personally and is now working to apply the policy to the entire team.

**Comment by Enshaedn** [comment]
It appears that CloudWatch access has been provided to the entire team. At least I can see logs for myself, Zak, and Jon.

**Comment by Enshaedn** [comment]
Closing since it was resolved. Thanks, Amy!
