### ISSUE TITLE
Automate the configuration of API gateway prod endpoint

### ISSUE THREAD

**Issue by dashinay** [ActoKids/devops#28]

**Comment by amy61789** [comment]
Automation Task - configuration of API Gateway prod endpoint 
1. Create CName in Route 53
2. API Gateway needs to use the new Name + SSL Certificate
3. Configure the API Gateway to print to cli for name

Estimated time: 6 hours

**Comment by amy61789** [comment]
Reference for [API Gateway Automation](https://andydote.co.uk/2017/03/17/terraform-aws-lambda-api-gateway/)

[Pull Request](https://github.com/ActoKids/devops/pull/39)

[Wiki](https://github.com/ActoKids/devops/wiki/Terraform-API-Gateway-Configuration)

How to install (assuming you already have Terraform installed)
1. [Clone Repo](https://github.com/ActoKids/devops)
2. Configure AWS credentials
3. Initialize Terraform
4. Then use 'terraform plan' command
5. Finally, apply the plan by typing 'terraform apply'

How to test:
After the command "terraform apply" check your AWS console for CNAME (Route 53), configured API Gateway, and the gateway points to the Lambda function.


Actual Time: 8 hours

**Comment by amy61789** [comment]
Bugs Worked On:
[#36 ](https://github.com/ActoKids/devops/issues/36)
[#80](https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/80)

**Comment by LyndonP** [comment]
I've tested this code and verified it works as intended. 
Create CName in Route 53
API Gateway needs to use the new Name + SSL Certificate
Configure the API Gateway to print to cli for name

This script does indeed instantiate the API teams resources in AWS and does the integration as well.
