### ISSUE TITLE
Terraform script ( S3 bucket for website)

### ISSUE THREAD

**Issue by LyndonP** [ActoKids/devops#3]

**Comment by amy61789** [comment]
Create Terraform script to build s3 infrastructure using HCL language 
Estimated Time: 1 hour

**Comment by amy61789** [comment]
Able to deploy demo s3 bucket to AWS team account using terraform.Uploaded scripts to GitHub ActoKids/devops repository.I use Terraform regularly for work, so this was pretty simple.

Actual Time: 15 minutes

**Comment by amy61789** [comment]
Link to s3 bucket: https://s3.console.aws.amazon.com/s3/home?region=us-east-2#
Script: https://github.com/ActoKids/devops/tree/dev/scripts/s3terraform

**Comment by toddysm** [comment]
Few things:
- Is there a Wiki page describing how this is intended to work?
- Who tested this and where is the feedback?
- What did you test and what is your feedback?

**Comment by amy61789** [comment]
[Wiki Page](https://github.com/ActoKids/devops/wiki/Terraform-s3)

Unfortunately I did not make a pull request in order for this to be reviewed. I tested it myself on an personal AWS account.
