### ISSUE TITLE
Automate the configuration of API gateway 1Box endpoint

### ISSUE THREAD

**Issue by dashinay** [ActoKids/devops#30]
**Task Description**
1. Create CNAME in Route 53
2. Configure API GW with SSL and CNAME
3. Point API GW to Lambda function

**Repo**
- https://github.com/ActoKids/devops/tree/dev/scripts/api-gw-1box

**Wiki**
- https://github.com/ActoKids/devops/wiki/Sprint-4-API-Gateway-Automation-in-1Box-environment

**Estimated Hours** - 7hours
**Actual Hours** - 8hours

**Comment by Enshaedn** [comment]
Let me know if you need any help/advice with the process in general. 

[Manual process ticket](https://github.com/ActoKids/api/issues/39)

**Comment by Stakada** [comment]
I fixed this bug : https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/84
