### ISSUE TITLE
Automate the configuration of UI 1Box endpoint

### ISSUE THREAD

**Issue by dashinay** [ActoKids/devops#33]
This task is to automate the configuration of the UI team 1box endpoint using terraform.

The terraform code should create a S3 bucket and an SSL certification and configure Route53 along with CloudFront.

Estimated time: 8 hours
Actual time spent: 5 hours on terraform + 3 hours working with the web UI team on the 1box endpoint set up in AWS.

1st task for Spring 4: PR: https://github.com/ActoKids/devops/pull/54
Wiki: https://github.com/ActoKids/devops/wiki/How-to-use-terraform-for-UI-endpoint-automation

2nd task for Sprint 4: Issue link: https://github.com/ActoKids/devops/issues/44

I've reviewed my teammate's web UI prod automation PR request for Spring 4.
Peer review: https://github.com/ActoKids/devops/tree/dev/automation/ui-prod-endpoint-automation

Bugs and requests that have been resolved/completed for Sprint 4:

https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/81 - issued a secret access key to have the team operate with EC2 per Michael's request.
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/82 - modified the Lambda policy for the crawler team to enable the privilage "InvokeFunction" per Ryan's request.
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/83 - created 3 Lambda functions for the crawler team per Nick's request.
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/86 - created a new Lambda function per Michael's request.
https://github.com/ActoKids/AD440_W19_CloudPracticum/issues/88 - helped increase the timeout from 3 seconds to 15 minutes per Nick's request.

Results:
![1](https://user-images.githubusercontent.com/38123178/54066761-ba952500-41ea-11e9-92d6-c4372b6dc6d3.PNG)
![2](https://user-images.githubusercontent.com/38123178/54066762-ba952500-41ea-11e9-9b87-46fed11e947f.PNG)
![3](https://user-images.githubusercontent.com/38123178/54066763-bb2dbb80-41ea-11e9-9280-243ffe76badc.PNG)
![4](https://user-images.githubusercontent.com/38123178/54066764-bb2dbb80-41ea-11e9-9bf3-c3858f53421e.PNG)
![5](https://user-images.githubusercontent.com/38123178/54066765-bbc65200-41ea-11e9-96a6-e9bc983ba7e4.PNG)

**Comment by jams2018** [comment]
@ActoKids/webui 

Can you guys help me figure out this issue?
As we discussed in the class, it should create and point Route53 to a path and assign it to S3 resource.

It would be great if you could add your input here.
