### ISSUE TITLE
Certificate Manager - AWS Oregon Region Access for Travis and Zak

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/devops#34]
Relating to the following tasks:
[Configure API Gateway Dev endpoints](https://github.com/ActoKids/api/issues/38)
[Configure API GateWay Production Endpoint](https://github.com/ActoKids/api/issues/37)

Travis and Zak need access to Certificate Manager for Oregon region. We need this access in order to be able to create a certificate for the Dev and Prod endpoints. 

<img width="1274" alt="certificatemanager_accesserror" src="https://user-images.githubusercontent.com/22527777/53537187-fb3fc080-3abd-11e9-94c2-6fe9055ad9d8.PNG">

**Comment by ZakBrinlee** [comment]
Travis and I also need access to API Gateway for Oregon region. 

<img width="1272" alt="api-gateway_access" src="https://user-images.githubusercontent.com/22527777/53540883-3648f080-3acc-11e9-9059-b5ef52c6176c.PNG">

**Comment by LyndonP** [comment]
To resolve the ACM part of this bug, I added the following lines to the ad440-w19-acm-useast2-"policy" policy:
        {
      "Effect": "Allow",
      "Action": "acm:*",
      "Resource": "arn:aws:acm:us-west-2:<SCHOOL_INFO_REMOVED>:certificate/*"
        }
This addressed both ZakB and TravisT's issue. I could have added these lines to individual users policies, but multiple members 
needed the same access, hence granting access at the "team" level.

To resolve the Route53 part of this bug, and for the sake of time, meeting the Sprint deadline, and security, I went ahead and 
created the following Record Sets in Route53:
    CNAME 
    Alias Record

![image](https://user-images.githubusercontent.com/34604046/53611070-0c520580-3b82-11e9-8def-dca1d65589c1.png)

**_Limiting access to Route53 to the DevOps team should be a serious consideration for security measures around the ActoKids org site._**

**Time Spent: 20 minutes**

### **Testing**
I tested this out with test-user2 and verified that the API team didn't have that access. Here is how I reproduced the issue:

**- Environment:**
AWS Console
MAC
AWS Certificate Manager

**Steps to reproduce**
Logged in with test-user2 who had been assigned to the API Team group on the AWS school account

**What do you expect to happen**
Have the ability to create a certificate 

**What actually happens**
![image](https://user-images.githubusercontent.com/34604046/53610976-c301b600-3b81-11e9-9927-de697f26ef88.png)

**Diagnostics and others**
Confirmed that Travis receives this error too.

**Comment by LyndonP** [comment]
![bug](https://user-images.githubusercontent.com/34604046/53610577-44584900-3b80-11e9-903f-2173e3742447.jpg)

**Comment by T-travis** [comment]
I can confirm Lyndon gave me permissions for the certificate manager and helped me complete my task of creating a production endpoint.  Issue is ok to be closed for me.

**Comment by LyndonP** [comment]
Received confirmation that this bug is resolved, closing issue.
