### ISSUE TITLE
Prod domain cert needs permissions for testing.

### ISSUE THREAD

**Issue by T-travis** [ActoKids/devops#35]
I created the production url, api.2edusite.com, for this sprint4.  Because it is production it is in Oregon and I don't have permission to make a lambda to test it works.  I am working with Lyndon from DevOps to solve this and recording the bug here.

**Comment by T-travis** [comment]
I can confirm Lyndon gave me permissions for the lambda to do testing in Oregon region and helped me complete my task of creating a production endpoint.  Issue is ok to be closed for me.

**Comment by LyndonP** [comment]
To resolve the ACM part of this bug, I added the following lines to the ad440-w19-lambda-uswest2 policy:

        {
          "Version": "2012-10-17",
            "Statement": [
        {
            "Effect": "Allow",
            "Action": "lambda:*",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestedRegion": "us-west-2"
                }
            }
        }
    ]}

This addressed TravisT's issue. I added these lines directly to Travis user policy, to bypass the 10 policy limit on AWS. But I have confirmed that 
Travis now has access.

**### Testing**
I tested this out with test-user2 and verified that the API team didn't have that access. Here is how I reproduced the issue:
**- Environment:**
AWS Console
MAC
Lambda

**Steps to reproduce**
Logged in with test-user2 who had been assigned to the API Team group on the AWS school account

**What do you expect to happen**
Have the ability to create a Lambda funcction in the us-west-2 region.

**What actually happens**
![bug2](https://user-images.githubusercontent.com/34604046/53677505-b48cca80-3c65-11e9-9abd-ea926c9b7030.png)
 


**Diagnostics and others**
Confirmed that Travis receives this error too. Testing with test-user2.

### **Estimated Time: 40 minutes
Time Spent: 40 minutes
URL:  https://api.2edusite.com/v1/events**

**Comment by LyndonP** [comment]
Received confirmation that this bug is resolved, closing issue.
