### ISSUE TITLE
Lambda Function permissions for Oregon Region - Dev endpoint

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/devops#36]
Relating to Issue:
[Configure API Gateway Dev endpoints #38](https://github.com/ActoKids/api/issues/38)

### BUG Issue**
I am unable to create a Lambda function to connect to the api-dev.2edusite.com domain for the Development environment. The purpose of this function is for testing and future dev deployments. :

**- Environment:**
AWS Console
Windows
AWS Lambda Management Console

**Steps to reproduce**
Logged in as zbrinlee@gmail.com student account
AWS Lambda Management Console - Create function
Fill out required fields - Select Create

**What do you expect to happen**
Lambda Management Console creates the Lambda Function as specified and allows full editing and testing. 

**What actually happens**
![api-dev-lambdafunctioncreateissue](https://user-images.githubusercontent.com/22527777/53619676-03bef680-3ba5-11e9-908b-7fe10386c4b6.PNG)

**Diagnostics and others**
NA

**Comment by amy61789** [comment]
I gave Lambda access to the API team per policies/roles. 
The team is not able to create or delete functions - if you are requesting a new Lambda resource be created the DevOps team will need to do that (please include your specifications).
API Team is also allocated to resources in the us-east-2 (Ohio) region.

**Comment by dashinay** [comment]
I don't know if we are allowed to give a permission to create a Lambda function. If you need to create a test function for this task I can create it for you and allow for full editing. Also I have already set up a Travis CI pipeline for dev deployment to a Lambda function "ak-api-dev-lbd" in Ohio region. If you would like to create testing only lambda function then as Amy said please, gave us your specification.

**Comment by ZakBrinlee** [comment]
Hello Amy and dashinay, 

 I will need a lambda function created in the Oregon region with the specification listed in the screenshot above. 

Once that is created I can edit it and do what I need to. 

Thanks

**Comment by dashinay** [comment]
Sorry for the delay, I have created the function you requested in the Oregon region. Could you check it and tell me if you have issues with it. Thanks

**Comment by ZakBrinlee** [comment]
Hello Dawit, 

 I am able to see and open the Lambda Function, but I am unable to do anything else. Please see attached screenshot for error from AWS about missing permissions. Thanks!
![lambdaerrorpermissions](https://user-images.githubusercontent.com/22527777/53698973-30872f80-3d98-11e9-83ea-6e26e1cf6b50.PNG)

**Comment by dashinay** [comment]
I have added permission for this specific lambda function. Could you try to access it again?

**Comment by ZakBrinlee** [comment]
I am able to edit the Lambda but it is still showing permission issues when trying to add it to an API Gateway endpoint method. 

- Environment:
AWS Console
Windows
AWS API GateWay Console

-Steps to reproduce
Logged in as zbrinlee@gmail.com student account
AWS API GateWay Console - **ak-api-dev-gateway** API selected
Select -> Resources tab =>**/events** => **GET**
Select **Integration Request**
Select the pencil icon next to: **Lambda Function : ak-api-dev-url-lambda** 
Select the **check mark** icon to confirm
See Error below

![aws-apigw-lambdapermissionerror](https://user-images.githubusercontent.com/22527777/53708868-3e65a080-3dea-11e9-97a0-88a0cbe20fc1.PNG)

This should be the last thing to the endpoint. If given the permission I can do it, or follow my steps and confirm it assigns the endpoint method to the Lambda function without any permissions errors. 

Thanks again!

**Comment by dashinay** [comment]
I have reproduced your steps and figured out the issue and updated the policy permissions. I have confirmed that by following the steps you provided there is no longer permission error. Would you, too, confirm it works and let me know. Thanks

**Comment by ZakBrinlee** [comment]
It is working now!

Thank you!

The endpoint is showing as it should from the Lambda function. This issue is no longer needed on my end.
