### ISSUE TITLE
TravisCI - Probable Bug

### ISSUE THREAD

**Issue by Enshaedn** [ActoKids/devops#37]
During the course of Sprint 4 and manually creating API endpoints it was noticed that the team needed permission for the US West-2 (Oregon) region so that they could create Lambda functions and API Gateways to properly ensure the custom domains were setup.

It was understood that our team shouldn't have Lambda/Dynamo access in the Oregon region because that is where TravisCI deploys for the dev and prod branches. API Gateway is a little tougher and seems reasonable for us to have had access to setup accurately. I feel like with us, even temporarily, getting access to Oregon for Lambda breaks the TravisCI pipeline concept. I went exploring in the class AWS account and noticed that TravisCI does not appear to be pushing to either dev or prod in Oregon.

There are two functions in Oregon's Lambda, but I can't see what they are. One is labeled test and the other is ak-api-prod-url-lambda. Neither one appears to be coming from TravisCI. However, there is a function (ak-api-dev-lambda) in the 1box region (Ohio) which is being updated by TravisCI and is labeled dev. If this is supposed to be the dev Lambda function it is being created in the wrong region by TravisCI and needs to be corrected. 

Note: If TravisCI was properly pushing to dev and prod in Oregon we wouldn't have need to create Lambda functions for testing and could have just used those.

**Comment by LyndonP** [comment]
Added the DynamoDB Lambda role to resolve this issue. Added the same rule to ALL the other API Lambdas.
