### ISSUE TITLE
API dashboard for PROD

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#50]

**Comment by amy61789** [comment]
Automate the API Dashboard for production using Terraform
Estimated Time: 4 hours

**Comment by amy61789** [comment]
Resource: Medium - ["Fumbling through a Lambda Deploy with Terraform"](https://medium.com/@seclectech/fumbling-through-a-lambda-deploy-with-terraform-ee4d21484d49)

[Pull Request](https://github.com/ActoKids/devops/pull/58)

[Wiki](https://github.com/ActoKids/devops/wiki/Terraform-Dashboard-Automation)

[Bug](https://github.com/ActoKids/devops/issues/60)

Actual Time: 4 hours
