### ISSUE TITLE
Production environment Lambdas for API Team

### ISSUE THREAD

**Issue by ZakBrinlee** [ActoKids/devops#53]
Request:
- 5 Lambda Functions in the Oregon region with the following naming conventions.  
   - ak-events-get-lambda
   - ak-events-post-lambda
   - ak-events_id-get-lambda
   - ak-events_id-put-lambda
   - ak-events_id-delete-lambda

Purpose:
For the client demo, the production environment needs 5 different endpoint Lambdas for each action from the UI. Currently, there is only 1 Lambda that was created for the Sprint 4 production environment setup/demo. 

Once we have these we can configure the API Gateway to the correct regional Lambdas for the final production environment demo.

**Comment by LyndonP** [comment]
To resolve this bug, I created these Lambda functions, and I also verified the correct permissions were given to the Lambdas themselves to run properly.
Estimated Time: 15 Minutes
Actual Time: 15 Minutes
