### ISSUE TITLE
Travis CI will need to install npm packages for some lambdas

### ISSUE THREAD

**Issue by T-travis** [ActoKids/devops#57]
Travis CI will need to install npm packages for some lambdas.  I talked to Lyndon and this may be happening but I could not find out for sure if it will happen.  Some of our lambda functions have additional npm packages that should be installed by Travis CI using package-lock.json or package.json which will be in the api branch.  Here is a [link](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) if for reference.  I recommend testing this out so we don't have last minute failures do to missing modules.  Thanks

**Comment by dashinay** [comment]
My understanding was that you want the npm install to be included into the travis yaml to install dependencies. I don't see a reason to have npm install packages as those dependencies are only used to build(which are used for testing) lambdas in Travis CI and doesn't get deployed with the function. As I saw in crawler team, for dependencies to be deployed with the function it needs to be in zip package form. Link to one of the package in crawler team - https://github.com/ActoKids/web-crawler/tree/dev/scripts/lambda/production/google/target%20package.

**Comment by T-travis** [comment]
Dawit fixed this so now I can have a .zip file in place of the index.js file in the lambda folder.
