### ISSUE TITLE
Updates to files in S3 bucket may take up to 24 hours to take effect

### ISSUE THREAD

**Issue by MrSamsa42** [ActoKids/devops#59]
Changes to files in an s3 bucket that serves a static website behind a CloudFront distribution may take up to 24 hours to take effect.  This is because the default TTL for files cached in CloudFront edge locations is 24 hours.  This could be an issue as updated files are pushed to the bucket serving the prod site.
More info here: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/UpdatingExistingObjects.html

and here:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html#invalidating-objects-api

If devops has already accounted for this, then please disregard and close this issue.

**Comment by jams2018** [comment]
When an invalidation request is made with an asterisk, any update will take effect as soon as the invalidation takes place. (less than a minute).
