### ISSUE TITLE
Travis CI Dev environment -> dev Lamdba - API

### ISSUE THREAD

**Issue by LyndonP** [ActoKids/devops#6]
Task is to set up CI for dev branch of Api team repository with Travis CI. 

Estimated time:  7hrs
Actual time spent:  10hrs

**Comment by bmenaz** [comment]
Need to add  .travis.yml file to api team repository to connect Travis CI and set up continuous build and deploy to Lambda servers.
In the process of creating yaml file and configuring it, missing the api script in the repository. Waiting for the IAM permissions for continuous deployment.

**Comment by bmenaz** [comment]
- Obtained  access and secure keys and lambda role. 
- Set up the yaml file for Travis CI and connected the repository to the service. Was able to configure the Travis deploy of alex’s post lambda script. 
- [travis ci build](https://travis-ci.org/ActoKids/api/jobs/489229318)
- [travis code](https://github.com/ActoKids/api/blob/dev/.travis.yml)

![lbd_fn](https://user-images.githubusercontent.com/38149440/52753759-dec76280-2fac-11e9-96d1-1d4507c52366.png)

- This link was helpful in configuring yaml file for node js script
[js with nodejs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#default-build-script)
[Setting up a CI/CD pipeline with Travis CI for a Serverless app](https://medium.com/a-man-with-no-server/setting-up-a-ci-cd-pipeline-with-travis-ci-for-a-serverless-app-e98b0e57d30c)

Pull Request: https://github.com/ActoKids/api/pull/29
[Wiki](https://github.com/ActoKids/api/wiki/Travis-CI)

**Comment by toddysm** [comment]
Please link to the following:
- Pull Request (you can do that when closing the task/issue)
- Wiki documentation how to do the build, what configuration is required etc.
- Test results and issues you have filed

**Comment by toddysm** [comment]
Few other comments:
- You are deploying different files to different lambdas, we should be deploying all the files to the DEV lambda.

**Comment by bmenaz** [comment]
I provided the pull request and had included the wiki page.
I fixed up the issue with deployment to different lambdas.
Code was reviewed and approved by two people Alex and Dawit.
