### ISSUE TITLE
Travis CI for API team

### ISSUE THREAD

**Issue by Stakada** [ActoKids/devops#61]
Bug: travis pipeline don't recognize branch.
<img width="1107" alt="Screen Shot 2019-03-19 at 4 02 57 PM" src="https://user-images.githubusercontent.com/34498187/54722967-34021100-4b23-11e9-8ea6-762dad2c0240.png">
<img width="1395" alt="Screen Shot 2019-03-20 at 11 09 59 AM" src="https://user-images.githubusercontent.com/34498187/54723004-54ca6680-4b23-11e9-94ae-5fe9424d3de0.png">

**Comment by dashinay** [comment]
Issue seems to be with the indentation on the yaml file. Check for the extra white-spaces and make sure branch is indented.

**Comment by Stakada** [comment]
Fixed. Thank you Dawit.
