### ISSUE TITLE
Dynamodb Terraform needs an Environment tag.

### ISSUE THREAD

**Issue by jams2018** [ActoKids/devops#63]
@LyndonP 

Can you update the terraform code for dynamodb with an Environment tag?

Link: https://github.com/ActoKids/devops/blob/dev/scripts/dynamodbterraform/dynamodb.tf

**Comment by LyndonP** [comment]
![image](https://user-images.githubusercontent.com/34604046/54725477-767c1b80-4b2c-11e9-8cda-7f96eca1b732.png)
 
Added the Environment variables.
