### ISSUE TITLE
Billing (Lambda function that pulls billing data)

### ISSUE THREAD

**Issue by LyndonP** [ActoKids/devops#7]
• Create cost.js that gets billing information of the day
• Create Lambda function
• Create API Gateway 
• Use Cloud Watch to trigger the lambda function

**DONE**
• Updated code.js so that time duration will be dynamically generated based on the day. 
• Researched JavaScript IAM api
• Created Wiki for billing
• Created Resource Group for DevOps
• Created Lambda function. ( need a group or policy for configuration)

**Estimated Time** : 10 hours
**Time Spent** : 5 hours
**Link** : 
       • lambda function (need configuration) https://github.com/ActoKids/devops/blob/dev/billing/cost.js
**WIKI** : https://github.com/ActoKids/devops/wiki/AWS.JavaScript-CostExplorer-API

**Comment by toddysm** [comment]
Need a few things:
- More comments in your code
- We need to work on the functionality - the information should be downloaded to some storage and not printed on the console
- Who tested this and what is the feedback?
- What did you test and what is your feedback?
